[package]
authors = ["Uzaaft <muaf@nmbu.no>"]
name = "rent-rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "maturin_starter"
crate-type = ["cdylib"]

[dependencies]
linfa-linear = "0.5.0"
linfa-logistic = "0.5.0"
pyo3 = { version = "0.15.1", features = ["extension-module"] }
